### ISSUE TITLE
ami tags not resolved by aegea

### ISSUE THREAD

**Issue by alperyilmaz** [czbiohub/packer-images#50]
Hi,
When I run 
```
aegea launch --iam-role S3fromEC2 --ami-tags Name=czbiohub-reflow -t t2.micro alper-test
```

I get the following error:
```
aegea.util.exceptions.AegeaException: Could not resolve AMI {'ami': None, u'Name': u'czbiohub-reflow'}
```
After that, I headed to AWS Console and searched for AMI using the "czbiohub-reflow" or even "czbiohub" as queries and there were no results. I thought it might be zone issue and I did the search on us-east-1, us-east-2,us-west-1 and us-west-2 (my default region) but I couldn't find AMI ID for "czbiohub".

Then I thought maybe the AWS Console AMI search might not be searching in tag field. Then I installed `packer` and created AMI and I can see the label "packer-example 1546734166" in "My AMIs" menu. However, I can launch an instance with using AMI ID but AMI name fails.

```
$ aegea launch --iam-role S3fromEC2 --ami-tags Name="packer-example 1546734166" -t t2.micro alper-test2
Identity added: /home/alper/.ssh/aegea.launch.alper.n550.pem (/home/alper/.ssh/aegea.launch.alper.n550.pem)
Traceback (most recent call last):
  File "/home/alper/.local/bin/aegea", line 23, in <module>
    aegea.main()
  File "/home/alper/.local/lib/python2.7/site-packages/aegea/__init__.py", line 78, in main
    result = parsed_args.entry_point(parsed_args)
  File "/home/alper/.local/lib/python2.7/site-packages/aegea/launch.py", line 67, in launch
    args.ami = resolve_ami(args.ami, **ami_tags)
  File "/home/alper/.local/lib/python2.7/site-packages/aegea/util/aws/__init__.py", line 389, in resolve_ami
    raise AegeaException("Could not resolve AMI {}".format(dict(tags, ami=ami)))
aegea.util.exceptions.AegeaException: Could not resolve AMI {'ami': None, u'Name': u'packer-example 1546734166'}
```

So, I am stuck. I'm sure the solution is very simple but I couldn't figure it out. How can I use czbiohub AMIs with aegea?

**Comment by jamestwebber** [comment]
The `czbiohub` AMIs are not currently made public, so the README only works for people within the organization. Sorry for the confusion.
